# Generated by Django 4.0.1 on 2022-09-13 12:23

import ads.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(validators=[ads.validators.check_birth_date]),
        ),
    ]
